### ISSUE TITLE
UpdateRemotePlugins throws error

### ISSUE THREAD

**Issue by revolter** [critiqjo/lldb.nvim#46] opened 2017-01-28 21:26 UTC
Running `:UpdateRemotePlugins` throws the error:

```
function remote#host#UpdateRemotePlugins[6]..<SNR>40_RegistrationCommands[15]..remote#host#Require[13
]..provider#pythonx#Require, line 14
Vim(let):E902: "" is not an executable
function remote#host#UpdateRemotePlugins[6]..<SNR>40_RegistrationCommands[15]..remote#host#Require[13
]..provider#pythonx#Require, line 21
Vim(for):E121: Undefined variable: channel_id
remote/host: generated rplugin manifest: /Users/revolt/.local/share/nvim/rplugin.vim
```

**Comment by critiqjo** [comment] 2017-01-31 12:19
What does `:echo has('python')` output?

**Comment by revolter** [comment] 2017-01-31 15:43
It outputs `1`.

**Comment by critiqjo** [comment] 2017-01-31 17:06
Hmm... Does the plugin work after restarting Neovim?

**Comment by critiqjo** [comment] 2017-01-31 17:08
Wait a second... The error log has nothing that points to `lldb.nvim`... Why do you think `lldb.nvim` is the cause of this error?

**Comment by revolter** [comment] 2017-01-31 21:07
> Does the plugin work after restarting Neovim?

I didn't manage to get it working at all.

> The error log has nothing that points to lldb.nvim... Why do you think lldb.nvim is the cause of this error?

Well, I initially thought that the `:UpdateRemotePlugins` command is `lldb.nvim` specific, and I didn't use it before at all. Also, running `:LLsession new` throws the `E492: Not an editor command: LLsession new`. Though `:help lldb-start` works.

**Comment by nfnty** [comment] 2017-01-31 22:05
This seems like a sourcing issue. Are you using a plugin manager? Try using [dein](https://github.com/Shougo/dein.vim).

**Comment by revolter** [comment] 2017-01-31 22:09
I'm using vim-plug.

**Comment by critiqjo** [comment] 2017-02-01 03:58
`vim-plug` should work fine... May be it's the error most Mac users are experiencing --- incompatible Python versions. In order to `import lldb`, you need to have Neovim use the built-in python, not the brewed one. So if that's not the case, loading `lldb.nvim` may fail.

But before going in that direction, can you check if you comment out the vim-plug line that loads `lldb.nvim`, whether the error still persist. (As I said before, check if this is indeed the cause of error.) If it persists, then comment it out again, and try to load another remote plugin, say, [deoplete](https://github.com/Shougo/deoplete.nvim) (requires python3; I couldn't find any python2 remote plugins).

**Comment by revolter** [comment] 2017-02-01 08:10
Commented the `lldb.nvim` plug and running `:UpdateRemotePlugins` prints:

> remote/host: generated rplugin manifest: /Users/Iulian/.local/share/nvim/rplugin.vim

I saw a couple of info regarding mac problems but none helped.

**Comment by critiqjo** [comment] 2017-02-01 09:20
I'm not sure how Neovim loads python2, but I'll guess it's using `env`. Assuming it is, can you test how these commands go:

```
$ env python2
>>> import lldb
```

To check whether `lldb` is available from the default python2.

**Comment by revolter** [comment] 2017-02-01 20:22
```
>>> import lldb
Fatal Python error: PyThreadState_Get: no current thread
[1]    29272 abort      env python2
```

**Comment by critiqjo** [comment] 2017-02-02 06:54
This: http://blog.rplasil.name/2016/03/how-to-debug-neovim-python-remote-plugin.html

**Comment by revolter** [comment] 2017-02-02 08:28
And what do I do for step 2?

**Comment by critiqjo** [comment] 2017-02-02 11:18
Check whether you have another `python` executable in your XCode directory (shown in the post), and try `import lldb` from it, I guess. After following all those steps, Neovim will use XCode's python for all python2 plugins.

Closing this since the issue is the same.

**Closed by critiqjo** 2017-02-02 11:18 UTC

**Comment by revolter** [comment] 2017-02-02 11:46
I would be very grateful if you could help me with this because I already read that (1 year old) blog post.

`/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python` doesn't contain any python executable.

The issue is the same to what?

**Comment by critiqjo** [comment] 2017-02-02 11:49
Your Mac or XCode version may be different. Just locate where XCode is installed, and then `find` the python executable in it.

**Comment by revolter** [comment] 2017-02-02 11:56
`/Applications/Xcode.app` doesn't contain any python executable.

**Comment by revolter** [comment] 2017-02-02 11:57
Isn't there any Mac user/contributor/member that could help me?

**Comment by revolter** [comment] 2017-02-02 13:01
I'll donate $30.

**Comment by critiqjo** [comment] 2017-02-02 13:07
Lol! I don't collect donations! I'm not a Mac user either (which I think you guessed). Though it's flattering to see that you are willing to pay $30 to get this plugin working... I guess you'd have to find out where the python interpreter used in XCode is located somehow. May be look through the process tree and see the child processes while debugging something in it?

**Comment by revolter** [comment] 2017-02-02 13:31
@critiqjo, Yes, I noticed. I'll donate it to whoever helps me then.

I don't know much about underlying stuff like this. I don't know if Xcode even has a python interpreter. I was wondering if there are people that use this plugin on macOS Sierra, and if they do, what did they have to do in order to get it working, as clearly that information is missing from the documentation.

**Comment by Shougo** [comment] 2017-02-02 23:21
If you want to donate, neovim project is recommended.
lldb.nvim requres neovim.

https://www.bountysource.com/teams/neovim

**Comment by revolter** [comment] 2017-02-03 08:07
@Shougo, Got it. But first, I really need help with this one but it's beyond me.

**Comment by nateozem** [comment] 2017-04-30 12:29
Even though I'm not using `python3` for `lldb` and for me to fully load
`lldb.vim` plug-in, I'd need to resolve the following error:

	function remote#host#UpdateRemotePlugins[6]..<SNR>76_RegistrationCommands[15]..remote#host#Require[13]..provider#pythonx#
	Require, line 14
	Vim(let):E902: "" is not an executable
	function remote#host#UpdateRemotePlugins[6]..<SNR>76_RegistrationCommands[15]..remote#host#Require[13]..provider#pythonx#
	Require, line 21
	Vim(for):E121: Undefined variable: channel_id

To fix this, I need to install `neovim` module for `python3` by using `pip` installer. 

	python3 -m pip install --user neovim

Once successfully installed and execute `:UpdateRemotePlugins` command back in
`neovim`, should see the following result:

	remote/host: python3 host registered plugins []

I wouldn't have to worried about `python (2.7.x)` as it is already installed
properly. As shown:

	remote/host: python host registered plugins ['lldb_nvim']
	remote/host: generated rplugin manifest: /Users/nate/.local/share/nvim/rplugin.vim

So the final results should look like this:

	:UpdateRemotePlugins

	remote/host: python3 host registered plugins []
	remote/host: python host registered plugins ['lldb_nvim']
	remote/host: generated rplugin manifest: /Users/nate/.local/share/nvim/rplugin.vim

**NOTE**: I'd assume this error isn't isolated only to `python3`, but also to `python
(2.7.x)` so install `neovim` module for this version if haven't done so.

	python -m pip install --user neovim

From what is described may not fix all problems to get `lldb.vim` plug-in
working. Refer to other issues that are closed.

**Comment by samvv** [comment] 2017-12-13 12:11
I was having issues with this as well, using macOS High Sierra. Just wanted to point out to anyone stumbling on this issue that you really need to make sure you are using the system python for LLDB, as explained in http://blog.rplasil.name/2016/03/how-to-debug-neovim-python-remote-plugin.html. Using a custom python, such as the one from Homebrew, will not work. As I understood it this is a bug in LLDB, which currently can only use the system python.

Tanks @revolter for giving me hints in other issues on how to fix it.
